### ISSUE TITLE
Wallpaper gone

### ISSUE THREAD

**Issue by erikdubois** [x-tabdeveloping/Edge-Dark#1]
I just tried your theme. It looks very promising.

But I do not know why but my wallpaper will be gone and the background becomes also grey/black.
All the info I think you might need is in the picture.
http://i.imgur.com/EDOUoWf.png

**Comment by x-tabdeveloping** [comment]
Hmm, it looks interesting. I haven't seen anything like this issue before. What desktop and GTK version do you use?

**Comment by Vistaus** [comment]
I have a similar issue. My wallpaper isn't gone but my wallpaper on the lock screen from LXDM (gnome-sccreensaver?) is. I'm using GTK 3.20.1 on Ubuntu GNOME 16.04 and my lock screen is, like I said, from LXDM (gnome-screensaver?). I'm using the latest Git version of Edge-Dark.

**Comment by x-tabdeveloping** [comment]
Did you get these issues only with my theme? It comes not, when you're trying Adapta?

**Comment by Vistaus** [comment]
I tried Adapta quickly recently and I don't think it happened there. It doesn't happen with any other theme either.

**Comment by x-tabdeveloping** [comment]
Okay, i will try to fix this problem. If you really want to use my theme, before the problem is fixed, try to install the xfdesktop package, and set it to autostart program. It works just fine with every desktop environment. But i'm working on.

**Comment by x-tabdeveloping** [comment]
Okay, try now. I did some changes. Sorry, but i can't check out, that the problem is fixed, or not, because i never got it.

**Comment by Vistaus** [comment]
xfdesktop is already installed. Pulled the latest commits and the problem is still there, unfortunately :frowning:

**Comment by x-tabdeveloping** [comment]
Okay, can you contact me via Hangouts, or anything other? I will try to fix, but i need somebody, who has the problem

**Comment by Vistaus** [comment]
I don't have/use Hangouts, sorry.

**Comment by x-tabdeveloping** [comment]
or anything else. What do you have?

**Comment by Vistaus** [comment]
I have Twitter, BBM, Skype. Why can't we do it through here?

**Comment by x-tabdeveloping** [comment]
We can do here too, but here will be lot of messages, but okay. Try to add this to gtk.css:

.nautilus-desktop{
background-color: transparent;}

**Comment by Vistaus** [comment]
Sorry if I may sound dumb, but doesn't that only do something if Nautilus is handling the desktop? In GNOME Shell, which I'm using, Nautilus doesn't handle the desktop.

**Comment by x-tabdeveloping** [comment]
I read somewhere the same issue, and there nautilus was the problem. https://github.com/Antergos/Numix-Frost/issues/14

**Comment by Vistaus** [comment]
Tried it and that didn't fix it, unfortunately :frowning:

**Comment by x-tabdeveloping** [comment]
Hmmm, i will check out, how it does work with my GNOME desk.

**Comment by x-tabdeveloping** [comment]
Okay, it seems like, when i apply desktop icons, the problem comes, i'll try to fix it.

**Comment by x-tabdeveloping** [comment]
Fixed, thanks for reporting!

**Comment by Vistaus** [comment]
It's not fixed here. I don't have any desktop icons either btw (disabled).

**Comment by x-tabdeveloping** [comment]
Then, there was not the same problem by you. The first one is actually fixed.
